### ISSUE TITLE
Double Jeopardy on every question

### ISSUE THREAD

**Issue by bentleyherron** [JMcWhorter150/backend_project#59]

**Comment by bentleyherron** [comment]
The timer also disappears when this bug happens.

**Comment by bentleyherron** [comment]
Confirmed with Show Number: 3862

**Comment by JMcWhorter150** [comment]
Old jeopardy episodes have a value of 100 instead of 200. Since my double jeopardy function compares the values of each question to the amount populated into the box, this causes every question to become a double jeopardy.
